name: Build and Deploy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            build-essential \
            libssl-dev \
            libffi-dev \
            libgl1-mesa-dev \
            zlib1g-dev \
            libncurses5-dev \
            libsqlite3-dev \
            libgdbm-dev \
            libbz2-dev \
            libreadline-dev \
            liblzma-dev \
            openjdk-11-jdk \
            unzip \
            git \
            curl

      - name: Install Buildozer and Cython
        run: |
          pip install cython
          pip install buildozer

      - name: Install Android SDK + Accept licenses
        run: |
          yes | sdkmanager --licenses || true
        env:
          ANDROID_SDK_ROOT: /usr/lib/android-sdk

      - name: Build APK
        run: |
          buildozer android debug
