name: Build and Deploy APK

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Set Python version (use Python 3.8 for better compatibility)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from your requirements.txt

      - name: Install dependencies for Kivy
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-pip build-essential libssl-dev libffi-dev python3-setuptools

      - name: Install Buildozer
        run: |
          pip install buildozer

      - name: Install Android SDK & NDK dependencies
        run: |
          sudo apt-get install -y openjdk-8-jdk
          sudo apt-get install -y unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools-linux-8512546_latest.zip -d $HOME/Android
          mkdir $HOME/Android/cmdline-tools
          mv $HOME/Android/cmdline-tools/* $HOME/Android/cmdline-tools/latest
          echo "y" | $HOME/Android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android --update
          echo "y" | $HOME/Android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android "platforms;android-29" "build-tools;29.0.3" "ndk;21.3.6528147"

      - name: Build APK
        run: |
          buildozer -v android debug  # Adjust this if you need a specific build type

      - name: Upload APK to Release (Optional)
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: "bin/*.apk"  # Adjust this if necessary to point to your APK file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
