name: Build and Deploy APK

on:
  push:
    branches:
      - main   # Change this to your default branch, e.g., "master" or "main"
  pull_request:
    branches:
      - main   # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use Python 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from your requirements.txt

      - name: Install dependencies for Kivy
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-pip build-essential libssl-dev libffi-dev python3-setuptools

      - name: Install Buildozer
        run: |
          pip install buildozer

      - name: Build APK
        run: |
          buildozer -v android debug  # Adjust this if you need a specific build type

      - name: Upload APK to Release (Optional)
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: "bin/*.apk"  # Adjust this if necessary to point to your APK file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
