name: Build and Deploy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Entire job timeout (optional but recommended)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Upgrade pip safely
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip setuptools wheel

      - name: Install Linux dependencies for Kivy & Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            build-essential \
            libssl-dev \
            libffi-dev \
            libgl1-mesa-dev \
            zlib1g-dev \
            libncurses5-dev \
            libsqlite3-dev \
            libgdbm-dev \
            libc6-dev \
            libbz2-dev \
            libreadline-dev \
            liblzma-dev \
            openjdk-11-jdk \
            unzip \
            git \
            curl

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade Cython
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK to GitHub Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: "bin/*.apk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
