name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install openjdk-11-jdk python3-venv zipalign
          pip install buildozer cython kivy

      - name: Generate Buildozer Spec File
        run: buildozer init

      - name: Build APK
        run: buildozer -v android debug --arch=arm64-v8a

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/
