name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip openjdk-17-jdk python3-pip python3-setuptools \
            python3-dev build-essential git libffi-dev libssl-dev \
            libsqlite3-dev zlib1g-dev libncurses5-dev libncursesw5-dev \
            libreadline-dev libgdbm-dev libbz2-dev liblzma-dev \
            libsqlite3-dev libjpeg-dev libfreetype6-dev

      - name: Install buildozer and Cython
        run: |
          pip install --upgrade pip setuptools wheel Cython
          pip install buildozer

      - name: Set environment for buildozer
        run: |
          echo "sdk.dir=$HOME/.buildozer/android/platform/android-sdk" >> local.properties

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: KalyanApp-APK
          path: bin/*.apk
